#!/bin/bash
# Turns on or off redshift at a certain temperature
# Usage: redshift-launcher temperature
# See redshift -h to get more information

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "" ]
then
        echo -e Usage: redshift-launcher $(tput sitm)[temperature]
        echo -e $(tput sgr0)See redshift -h to get more information
	exit
fi


if pidof redshift > /dev/null
then
	pkill redshift
else
	redshift -t $1:$1 -l 0:0 > /dev/null 2>&1 &
fi
